export const initialFormValues = {
  slices: [
    {
      option: "",
      image: {
        uri: "https://files.yosuite.com/media/modules-documents-models-document-documentmodel/68ff4a63c3c94dac0d0610bf/documents__attachment/ChatGPT%20Image%20Oct%2020,%202025,%2002_55_45%20PM-YKNaWS2qbO.png",
        offsetX: 0,
        offsetY: 0,
        sizeMultiplier: 1,
        landscape: false,
      },
      style: {
        backgroundColor: "#ff8f43",
        textColor: "#ffffff",
        fontFamily: "Arial",
        fontSize: 20,
        fontWeight: 400,
        fontStyle: "normal",
      },
      optionSize: 1,
    },
  ],
  mustStartSpinning: false,
  prizeNumber: 0,
  outerBorderColor: "#000000",
  outerBorderWidth: 5,
  innerRadius: 0,
  innerBorderColor: "#000000",
  innerBorderWidth: 0,
  radiusLineColor: "#000000",
  radiusLineWidth: 5,
  fontFamily: "Arial",
  fontSize: 20,
  fontWeight: 400,
  fontStyle: "normal",
  perpendicularText: false,
  textDistance: 60,
  spinDuration: 1000,
  startingOptionIndex: 0,
  disableInitialAnimation: false,
};