export const initialFormValues = {
  slices: [
    {
      type: "text", // Can be "text" or "image"
      option: "asds",
      image: {
        uri: "",
        offsetX: 0,
        offsetY: 0,
        sizeMultiplier: 1,
        landscape: false,
      },
      style: {
        backgroundColor: "#ff8f43",
        textColor: "#ffffff",
        fontFamily: "Arial",
        fontSize: 20,
        fontWeight: 400,
        fontStyle: "normal",
      },
      optionSize: 1,
    },
  ],
  mustStartSpinning: false,
  prizeNumber: 0,
  outerBorderColor: "#000000",
  outerBorderWidth: 5,
  innerRadius: 0,
  innerBorderColor: "#000000",
  innerBorderWidth: 0,
  radiusLineColor: "#000000",
  radiusLineWidth: 5,
  fontFamily: "Arial",
  fontSize: 20,
  fontWeight: 400,
  fontStyle: "normal",
  perpendicularText: false,
  textDistance: 60,
  spinDuration: 1000,
  startingOptionIndex: 0,
  disableInitialAnimation: false,
};